//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organiser
    {
        public int Id { get; set; }
        public string represent { get; set; }
        public string position { get; set; }
        public bool status { get; set; }
    
        public virtual User User { get; set; }
    }
}
