//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue_Booking
    {
        public int Id { get; set; }
        public int eventId { get; set; }
        public int venueId { get; set; }
        public System.TimeSpan startTime { get; set; }
        public System.TimeSpan endTime { get; set; }
        public bool status { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Venue Venue { get; set; }
    }
}
